name = "fortio"
version = "0.1.0"
license = "MIT"
author = "Fortio contributors"
maintainer = "krystophny@github"
copyright = "2026 Fortio contributors"

[build]
auto-executables = false
auto-examples = false
auto-tests = true
module-naming = false
link = ["pthread", "z"]

[install]
library = true

[library]
source-dir = "src"

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"
